### ISSUE TITLE
Request createWorkspace failed with message: 5 NOT_FOUND: cannot resolve base image: not found  Unknown Error: { "code": -32603 }

### ISSUE THREAD

**Issue by asgaraliyev** [hpssjellis/my-gitpod-android-install#2]
![image](https://user-images.githubusercontent.com/47985813/134206099-1af77f88-9dcd-406c-a985-c4507e7a8dc0.png)

**Comment by hpssjellis** [comment]
@asgaraliyev I havn't used this for a while, but when the title is changed the gitpod.yml file needs several things changed. Look for what was the old title and see if you can go from there.

**Comment by asgaraliyev** [comment]
Thanks for response
